### ISSUE TITLE
OSSのライセンスはなにになりますでしょうか

### ISSUE THREAD

**Issue by taisukeh** [ToQoz/SandS#2]
こちらのソースコード大変勉強になりました。ありがとうございます。

派生させたツールを作成しようと思うのですが、OSSのライセンスは何が適用されるでしょうか。

**Comment by toqoz** [comment]
@taisukeh 決めてなかったです… これを機に MIT License としました :pray: https://github.com/ToQoz/SandS/blob/master/LICENSE.md

**Comment by taisukeh** [comment]
ありがとうございます 🙇

**Comment by taisukeh** [comment]
ありがとうございます。こちらの実装を参考に、月配列という日本語入力の配列用のエミュレータを作成しました。
https://github.com/taisukeh/TsukiEmulator
